export const menuData=[
    {link:"Vehicles"},
    {link:"Energy"},
    {link:"Charging"},
    {link:"Discover"},
    {link:"Shop"},
    {link:"English"},
    {link:"Support"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    {link:"LogIn"},
    

    
]